import { Profile, Product, Category, Catalog, Order } from './supabase/types';

export const mockProfile: Profile = {
  id: 'store-douala-chic-01',
  user_id: 'user-01',
  nom_boutique: 'Douala Chic Boutique',
  slug: 'douala-chic',
  logo_url: 'https://images.unsplash.com/photo-1534452203293-494d7ddbf7e0?w=200&h=200&fit=crop&crop=faces',
  whatsapp_number: '237690123456',
  description: 'Mode femme, maroquinerie italienne et collections exclusives à Douala (Akwa). Prise de commande express.',
  devise: 'FCFA',
  plan: 'pro',
  adresse: 'Rue Prince Bell, Akwa',
  ville: 'Douala',
  pays: 'Cameroun',
  couleur_theme: 'olive',
  lookbook_media_url: null,
  lookbook_media_type: null,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const mockCategories: Category[] = [
  { id: 'cat-all', store_id: mockProfile.id, nom: 'Tout', ordre: 0, icon: '✨', created_at: new Date().toISOString() },
  { id: 'cat-robes', store_id: mockProfile.id, nom: 'Robes', ordre: 1, icon: '👗', created_at: new Date().toISOString() },
  { id: 'cat-vestes', store_id: mockProfile.id, nom: 'Vestes', ordre: 2, icon: '🧥', created_at: new Date().toISOString() },
  { id: 'cat-sacs', store_id: mockProfile.id, nom: 'Sacs', ordre: 3, icon: '👜', created_at: new Date().toISOString() },
  { id: 'cat-chaussures', store_id: mockProfile.id, nom: 'Chaussures', ordre: 4, icon: '👠', created_at: new Date().toISOString() },
  { id: 'cat-accessoires', store_id: mockProfile.id, nom: 'Accessoires', ordre: 5, icon: '⌚', created_at: new Date().toISOString() },
];

export const mockProducts: Product[] = [
  {
    id: 'prod-01',
    store_id: mockProfile.id,
    category_id: 'cat-vestes',
    nom: 'Tailored Blazer Coat Rouge Royal',
    description: 'Ce blazer long croisé à double boutonnage offre une silhouette nette et confiante avec une coupe sur-mesure moderne. Conçu en tissu infroissable premium pour les rendez-vous professionnels et cérémonies.',
    prix: 45000,
    prix_promo: 39500,
    discount_percent: 12,
    images: [
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800&auto=format&fit=crop&q=80',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Rouge Rubis', hex: '#B42544' },
      { name: 'Noir Anthracite', hex: '#2E2C24' },
      { name: 'Bleu Roi', hex: '#2B5797' },
      { name: 'Crème Soie', hex: '#F6F1E7' },
    ],
    rating: 4.9,
    reviews_count: 120,
    stock: 7,
    en_stock: true,
    actif: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-02',
    store_id: mockProfile.id,
    category_id: 'cat-robes',
    nom: 'Robe Blanche Soie Coucher de Soleil',
    description: 'Robe longue vaporeuse à col licou avec fente haute élégante. Idéale pour les réceptions, séances photos et soirées prestigieuses.',
    prix: 38000,
    prix_promo: 32000,
    discount_percent: 15,
    images: [
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&auto=format&fit=crop&q=80',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Blanc Pur', hex: '#FFFFFF' },
      { name: 'Beige Sable', hex: '#E4DAC4' },
      { name: 'Vert Émeraude', hex: '#097969' },
    ],
    rating: 5.0,
    reviews_count: 98,
    stock: 5,
    en_stock: true,
    actif: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-03',
    store_id: mockProfile.id,
    category_id: 'cat-sacs',
    nom: 'Sac à Main Cuir Royal Bordeaux',
    description: 'Cuir véritable italien travaillé à la main, boucle dorée gravée et bandoulière amovible.',
    prix: 28000,
    prix_promo: 24000,
    discount_percent: 14,
    images: [
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800&auto=format&fit=crop&q=80',
    ],
    sizes: ['Format Standard'],
    colors: [
      { name: 'Bordeaux', hex: '#6B1D2F' },
      { name: 'Noir Cuir', hex: '#1E1E1E' },
      { name: 'Camel', hex: '#C19A6B' },
    ],
    rating: 4.8,
    reviews_count: 64,
    stock: 4,
    en_stock: true,
    actif: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-04',
    store_id: mockProfile.id,
    category_id: 'cat-chaussures',
    nom: 'Escarpins Nude Talon Aiguille 8cm',
    description: 'Semelle intérieure rembourrée avec technologie confort toute journée.',
    prix: 22000,
    prix_promo: 18500,
    discount_percent: 16,
    images: [
      'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&auto=format&fit=crop&q=80',
    ],
    sizes: ['37', '38', '39', '40', '41'],
    colors: [
      { name: 'Nude Poudré', hex: '#E2C7B2' },
      { name: 'Noir Verni', hex: '#1A1A1A' },
      { name: 'Rouge Carmin', hex: '#9B1B30' },
    ],
    rating: 4.7,
    reviews_count: 42,
    stock: 6,
    en_stock: true,
    actif: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-05',
    store_id: mockProfile.id,
    category_id: 'cat-vestes',
    nom: 'Top Maille Texturée Olive & Or',
    description: 'Maille légère aérée, coupe décontractée ultra-tendance avec finitions soignées.',
    prix: 16000,
    prix_promo: null,
    discount_percent: 0,
    images: [
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&auto=format&fit=crop&q=80',
    ],
    sizes: ['Unique', 'M', 'L'],
    colors: [
      { name: 'Olive Clair', hex: '#8F9779' },
      { name: 'Beige Lin', hex: '#F0EAD6' },
    ],
    rating: 4.9,
    reviews_count: 31,
    stock: 9,
    en_stock: true,
    actif: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-06',
    store_id: mockProfile.id,
    category_id: 'cat-accessoires',
    nom: 'Montre Élégance Cadran Nacre & Or',
    description: 'Boîtier étanche 3 ATM, aiguilles dorées et bracelet réglable haute finition.',
    prix: 18000,
    prix_promo: 15000,
    discount_percent: 17,
    images: [
      'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&auto=format&fit=crop&q=80',
    ],
    sizes: ['Taille Unique (Ajustable)'],
    colors: [
      { name: 'Or Jaune', hex: '#D4AF37' },
      { name: 'Or Rose', hex: '#B76E79' },
      { name: 'Argent', hex: '#C0C0C0' },
    ],
    rating: 5.0,
    reviews_count: 85,
    stock: 12,
    en_stock: true,
    actif: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const mockCatalog: Catalog = {
  id: 'cat-01',
  store_id: mockProfile.id,
  titre: 'Collection Prestige 2026',
  slug_public: 'douala-chic',
  description: 'Découvrez nos nouveautés exclusives et commandez directement sur WhatsApp.',
  produits_ids: mockProducts.map(p => p.id),
  template: 'standard',
  actif: true,
  vues: 540,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const mockOrders: (Order & { items_count: number })[] = [
  {
    id: 'ord-01',
    store_id: mockProfile.id,
    customer_id: 'cust-01',
    catalog_id: mockCatalog.id,
    reference: 'KAT-01042',
    statut: 'envoyee_whatsapp',
    total: 39500,
    mode_paiement: 'a_la_livraison',
    nom_client: 'Mireille Kamga',
    telephone_client: '237670112233',
    adresse_livraison: 'Bonapriso, face Super U',
    notes: 'Taille M - Rouge Rubis',
    items_count: 1,
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ord-02',
    store_id: mockProfile.id,
    customer_id: 'cust-02',
    catalog_id: mockCatalog.id,
    reference: 'KAT-01041',
    statut: 'confirmee',
    total: 32000,
    mode_paiement: 'mobile_money',
    nom_client: 'Arnaud Talla',
    telephone_client: '237699445566',
    adresse_livraison: 'Makepe, rond-point Petit Pays',
    notes: 'Paiement MTN MoMo validé',
    items_count: 1,
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ord-03',
    store_id: mockProfile.id,
    customer_id: 'cust-03',
    catalog_id: mockCatalog.id,
    reference: 'KAT-01040',
    statut: 'livree',
    total: 50500,
    mode_paiement: 'a_la_livraison',
    nom_client: 'Carine Nkoa',
    telephone_client: '237655889900',
    adresse_livraison: 'Akwa Nord',
    notes: 'Colis livré avec succès',
    items_count: 2,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updated_at: new Date().toISOString(),
  },
];
